# Generated by Django 4.2.17 on 2024-12-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_delete_profile"),
        ("checkout", "0004_alter_orderlineitem_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="user.userprofile",
            ),
        ),
    ]
