# Generated by Django 4.2.17 on 2024-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image_url_product_rating_product_sku_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_sizes",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
