# Generated by Django 4.2.17 on 2024-12-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.TextField(default="testing"),
        ),
    ]
