# Generated by Django 4.2.17 on 2024-12-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="has_sizes",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
